### PR TITLE
Attempt to upgrade to NAN2

### PR DESCRIPTION
**Pull request by keeganbrown**
Passes tests locally on node 4.1.1. Doing this pull request to see if Travis will agree. There's a whole bunch of deprecation notices during the build process. Also -- to build with Node 4.1.1 requires a fairly recent C compiler -- it requires support for C++11. I used g++ 4.9 and gcc 4.9.

### CODE REVIEW

**Comment by keeganbrown** [comment]
Build Fails locally with node 0.12.7 also. super.

**Comment by peterbraden** [comment]
Is there any way to keep this backwards compatable?

**Comment by keeganbrown** [comment]
I'm pretty sure that this can be made backwards compatible, at least to node v0.12.x. Half the point of the rebuild of NAN in v2 (as I understand it) was to support backwards compatibility. The errors I've seen so far have to do issues regarding "v8::Handle" vs "v8::Local". After looking through the Nan2 commits, I see one where they're removing "Handle" and replacing it with "Local", so I'm trying that next.

**Comment by keeganbrown** [comment]
Side note -- I need to undo some unrelated changes I made in the process of testing, so this isn't ready to merge quite yet, if if the CI tests pass.

**Comment by keeganbrown** [comment]
Failed to build in node 0.10.40. doh.

**Comment by keeganbrown** [comment]
before I go too far down this particular rabbit hole, @peterbraden what versions of node are you supporting?

**Comment by keeganbrown** [comment]
w00t

**Comment by peterbraden** [comment]
I mean I'd like to keep 0.10 as per https://cdn-images-2.medium.com/max/1000/1*mgj_oxtasj3Minbx4_ElLg.png but I'm fine with just 0.12 as well. The matrix with opencv versions gets big pretty quick.

**Comment by peterbraden** [comment]
This is looking great btw, let me know when it's safe to give it a shot and merge it.

**Comment by keeganbrown** [comment]
Thanks! Glad to help out -- love your work. So my most recent commit is building in Node 0.10, 0.12, and 4.1 -- that looks all good. I added a vagrant folder with NVM for local testing purposes, I need to clean it up a little bit if you don't mind keeping it in there -- if you'd rather not, I can remove it.

**Comment by keeganbrown** [comment]
vagrant folder is cleaned up. if the tests pass, then it's good to merge as far as I'm, concerned. 
Another addendum -- I updated the buffers dependency as well as the node-pre-gyp dependency in the process (both minor version bumps). I don't think that should cause any problems, but just as an fyi.

**Comment by keeganbrown** [comment]
One other thought -- it's spitting out a bunch of deprecation warnings during the build process. Those should probably be cleaned up too at some point.

**Comment by keeganbrown** [comment]
@peterbraden My latest commit got rid of the deprecation warnings that were popping up when building in Node v4.1.2. This latest version is building correctly in Node v0.10, v0.12, and v4.1. I added a "vagrant" folder that I was using for testing -- there's not much in it, but I can remove it before you merge if you want to keep the repo cleaner. Otherwise, I think this is all good to merge.

**Comment by peterbraden** [comment]
Looks great, thanks!

**Pull request merged**
