### PR TITLE
Add support for lineType and offset for drawContours

### PR DESCRIPTION
**Pull request by BBB**
As in the title, this adds the 2 params to be passed into opencv.

### CODE REVIEW

**Comment by danschultzer** [comment]
Looks good, but it's diverging from the original C++ method: https://github.com/opencv/opencv/blob/05b15943d6a42c99e5f921b7dbaa8323f3c042c6/modules/imgproc/src/drawing.cpp#L2379

```
cv2.drawContours(image, contours, contourIdx, color[, thickness[, lineType[, hierarchy[, maxLevel[, offset]]]]])
```

Missing `hierarchy` and `maxLevel` arguments, before `offset`.

**Comment by BBB** [comment]
I'll try to get a chance to sort this out this week

**Comment by BBB** [comment]
@danschultzer Happy with that solution? The args aren't the same, but the user can alter the hierarchy within the contours object. This seemed to be the way it has been done elsewhere.

**Comment by danschultzer** [comment]
Yeah, it looks good, thanks :+1:

**Comment by sebastienroul** [comment]
Hi,

Working on the last version of opencv and node-opencv, and the offset parameter not seems to be used

`img.drawContour(contours, i, RED,  thickness, lineType, maxLevel, [100,100])`

The contours are drawn but from 0,0, and not 100,100.

Any idea ?

**Pull request merged**
