### PR TITLE
Fix issue with Linux binaries not passing self-test on install.

### PR DESCRIPTION
**Pull request by edgarsilva**
This was happening because OpenCV version in travis-ci was very old due to travis-ci using ubuntu 12.04.

Added new PPA and updated install OpenCV commands.

### CODE REVIEW

**Comment by edgarsilva** [comment]
Also Updated package version to v0.3.1 to avoid clash of pre-compiled binaries .

**Comment by Queuecumber** [comment]
The appveyor build failed, is that expected?

**Comment by edgarsilva** [comment]
I did not change anything for windows or appveyor, but it seems it is just a typo in the opencv folder name. I can check it out and fix it though.

**Comment by Queuecumber** [comment]
Ok if you find it's not a big deal let me know and I'll merge

**Comment by edgarsilva** [comment]
Could you pls re-run the appveyor build? nothing has changed so it might also be an appveyor issue. I'll fire up a windows machine in the meantime to check it out.

**Comment by Queuecumber** [comment]
I think @peterbraden has to do that

**Comment by edgarsilva** [comment]
@Queuecumber it seems it was a Chocolatey install issue, so it should be fine once we run the build again.

```
Write-Error : OpenCV did not finish successfully. Boo to the chocolatey gods!
-----------------------
[ERROR] Exception calling "GetResponse" with "0" argument(s): "Unable to connec
t to the remote server"
```

**Comment by Queuecumber** [comment]
@edgarsilva So should I just merge anyway or wait on @peterbraden to rerun the build

**Comment by edgarsilva** [comment]
You should just merge it, since it will not affect the appveyor issue anyways. The binaries for windows will not be affected until the 3.0.1 release is cut by @peterbraden.

The releae will create a new set of pre-compiled binaries for that version.

BTW I already fixed the linux binaries in the AS3 bucket for OpenCV 2.4.x with node-openxc 3.0.0, so there is not even a hurry for this to be released. It can wait till the next schedules release.

**Comment by Queuecumber** [comment]
Ok merged, thanks for the fix

**Comment by edgarsilva** [comment]
Sure, NP :+1:

**Pull request merged**
