### PR TITLE
6.0.0 release

### PR DESCRIPTION
**Pull request by danschultzer**
Diff: https://github.com/peterbraden/node-opencv/compare/5fb426aa1428b3d16e7fb0b1412f44410077382e...master

Updated CHANGELOG and bumped package.json.

I'll rebase this when #445 (and others) has been merged in.

Suggestions for other PR we should merge in before releasing:
- [x] #306

- [x] Review all PR's to see which needs to make it in this release

cc @peterbraden

### CODE REVIEW

**Comment by peterbraden** [comment]
I merged in 306 to master. The idea is to be able to test multiple opencv versions in docker, but I didn't get it finished, but having these dockerfiles is useful for that.

Let me take a look at the other ones too.

**Comment by danschultzer** [comment]
Sounds good :+1: I'll update the CHANGELOG with the merges.

**Comment by peterbraden** [comment]
I don't see any other candidates for an easy merge, so let's go with what we have now.

**Comment by danschultzer** [comment]
That's great :+1: One thing I noticed; #306 was merged into https://github.com/peterbraden/node-opencv/tree/fixes, and not to `master`. The PR was set up for the `fixes` branch.

Apart from that everything LGTM :rocket:

**Comment by peterbraden** [comment]
Published opencv@6.0.0

**Comment by danschultzer** [comment]
Added tag/release.

**Comment by danschultzer** [comment]
Hmm, I see that builds don't work as expected when tagging. I'll take a look at it when I get the chance.

**Pull request merged**
