### PR TITLE
Convert global scope declaration to local var

### PR DESCRIPTION
**Pull request by salomao-rodrigues**

### CODE REVIEW

**Comment by mvines** [comment]
Since you're already in here would you mind also doing the same for the `contours` variable too?

https://github.com/salomao-rodrigues/node-opencv/blob/9cca14830934fa775f27b6230e14709252ffd8b9/examples/contours.js#L27

**Comment by salomao-rodrigues** [comment]
Good shout, missed that one.

**Comment by mvines** [comment]
Cool, thanks.  Could you please squash those two commits into one though?

**Comment by salomao-rodrigues** [comment]
Was counting on you to "squash and merge" using the web ui option 😄 
Otherwise I'll squash myself tomorrow as I'm on the phone now. 👍

**Comment by mvines** [comment]
Oh sure

**Pull request merged**
