### PR TITLE
Opencv 3 3 support v2

### PR DESCRIPTION
**Pull request by thielsn**
Follow up for:
https://github.com/peterbraden/node-opencv/pull/556

@btsimonh 
I just did a rebase and merged the changes. However, I was not able to test it with a different version than  opencv 3.3.1-2 installed on my machine. So, someone should test this before adding to master, I guess.

Regards
Simon

### CODE REVIEW

**Comment by btsimonh** [comment]
Hi Simon, 
travis will check on cv 2.4 - I will try to test with 3.3.0 later this evening (happens to be what I have right now!).  (although travis died on node6, but node7 worked; so I just restarted the node6 job, and it went through).
I can't see an example in the examples folder which uses the facerecognizer - if you are using it, could you copy face-detection.js and change it to use face-recogniser in some way if easy to do?  Just something to exercise as much of the module as possible.  (all the examples are run at the end of formal tests, and so contribute towards both coverage and if they crash/throw we#'ll know if something is operationally broken....). - I'll need this to do more than just a 'will it compile' test later on 3.3.0 :).

thanks,
Simon

**Comment by thielsn** [comment]
Hi Simon,

actually, I must admit, I'm not using face recognition either. I was adapting the code mainly to make it compile for face detection with hair cascades. So, I wont be able to contribute any examples for this, sorry. 

Regards
Simon

**Comment by btsimonh** [comment]
ok I'll see if I can figure it out; hopefully some time soon...

**Comment by btsimonh** [comment]
Confirm builds ok on 3.3, 3.0 and 2.4
Too complex to write an example or test for right now.... so merging anyway :)

**Pull request merged**
