### PR TITLE
Dirty draft of using features2d for calculating

### PR DESCRIPTION
**Pull request by AVVS**
This is a PR accompanying #195.

### CODE REVIEW

**Comment by peterbraden** [comment]
Is this ready to merge, or is it still a draft?

**Comment by AVVS** [comment]
@peterbraden this works, but usually one comparison takes around 20ms and it's sync. Could you help me with making this operation async?

**Comment by AVVS** [comment]
@peterbraden now this is actually complete and working in non-blocking fashion. Therefore once builds pass it is safe to merge. Also it includes several upgrades to dependencies, which, I believe, are crucial (especially nan)

**Comment by peterbraden** [comment]
Thanks!

**Pull request merged**
