### PR TITLE
Add pre compiled binaries for windows, mac and linux

### PR DESCRIPTION
**Pull request by edgarsilva**
Adds pre compiled binaries for all 3 major platforms using node-pre-gyp. This is the same thing we did and are using in node-serialport, has worked great so far.

@peterbraden after merging I do need your help to generate the secure keys in travis and app-veyor (since they are repo and account bound respectively). We also need to create a new branch for OSX pre-compiled binaries called `osx-binaries`, since travis does not support multiple OS builds, so we need a different branch to compile for OSX.

I'm creating a pre-compiled-binaries.md file to describe the process, I'll also add a make task to make it easier to generate the binaries with each release.

BTW we at [The Hybrid Group](https://github.com/hybridgroup) ([hybridgroup.com](http://hybridgroup.com/)) are sponsoring the AS3 buckets, we also do it for node-serialport (as mentioned above) and we'll be adding them for [node-gamepad](https://github.com/creationix/node-gamepad).

Regards,

### CODE REVIEW

**Comment by peterbraden** [comment]
Hi @edgarsilva - sorry for the delay on this - What do I need to do to get the travis build working again?

**Comment by edgarsilva** [comment]
This is happening because the latest version of opencv in chocolatey for windows is a newer one than the one in in the ubuntu repos, let me add ad a validation to the bindings file to check for different versions in linux and windows.

**Comment by edgarsilva** [comment]
@peterbraden does node-opencv still works with opencv 4.3.1? or what is the minimum opencv version?

**Comment by edgarsilva** [comment]
Seems like I have fixed most of the issues, but tests are failing, do you have any idea what this is about:

```
$ npm test

> opencv@1.0.0 test /home/travis/build/hybridgroup/node-opencv

> node test/unit.js

TAP version 13

# Smoke tests / Can Import

libdc1394 error: Failed to initialize libdc1394

node: symbol lookup error: /home/travis/build/hybridgroup/node-opencv/build/opencv/v1.0.0/Release/node-v11-linux-x64/opencv.node: undefined symbol: _ZN7Calib3D4InitEN2v86HandleINS0_6ObjectEEE

npm ERR! Test failed. See above for more details.

npm ERR! not ok code 0

The command "npm test" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by Queuecumber** [comment]
@edgarsilva Just quickly looking it over it might be something from the Calib3D module I added. Did you merge the most recent commits to master?

**Comment by edgarsilva** [comment]
I did merge master like 30 mins ago, compilation was failing bfore that, now it works but tests fail, same behavior in my local if I build on my pc and run `npm test`.

I'm running opencv version 2.4.9.

**Comment by Queuecumber** [comment]
@edgarsilva Pretty weird stuff, I just ran `npm test` against my most recent pull request (#221) and I get all tests passed. It looks like I am on version 2.4.8, is it possible that one minor version change is causing the failure?

**Comment by edgarsilva** [comment]
@Queuecumber I pulled your latest changes deom commit #221 and `npm test` still fails with the same error on my computer:

```
$ npm test

> opencv@1.0.0 test /home/edgar/workspace/node-opencv
> node test/unit.js

TAP version 13
# Smoke tests / Can Import
node: symbol lookup error: /home/edgar/workspace/node-opencv/build/opencv/v1.0.0/Release/node-v11-linux-x64/opencv.node: undefined symbol: _ZN7Calib3D4InitEN2v86HandleINS0_6ObjectEEE
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

```

Trying with older version next.

**Comment by Queuecumber** [comment]
@edgarsilva When the compilation is running, do you see the Calib3D.cc file being compiled? Is it listed in your bindings.gyp?

**Comment by edgarsilva** [comment]
@Queuecumber nice catch! tests are now working on local, it seems I overwrote the file when merging master. Let me push to check in the CI tools.

**Comment by Queuecumber** [comment]
@edgarsilva Fantastic, that was a close one

**Comment by edgarsilva** [comment]
Build works now but I need to fix an issue with windows pre-compiled binary for the new sources, I will merge a PR to our master branch in our fork soon. It should be reflected here.

BTW I also added the changes included in your PR #221 to avoid any conflicts as you suggested above.

**Comment by Queuecumber** [comment]
@edgarsilva Ok so what's the best path forward in this situation, wait for #221 to be merged first and then have yours merged?

**Comment by edgarsilva** [comment]
Once I fix the issue with the windows pre-compiled binaries wand we merge this PR #221 will change nothing since those changes will be already included in here.

If we merge #221 first then this PR will not change that file, since they are the same, so both ways work, no biggie.

**Comment by edgarsilva** [comment]
There was also an issue with node-pre-gyp in some windows envs (windows 7) for which I have pushed a fix. This is ready to be merged, @peterbraden let me know when you have time to coordinate so Ic an give you the AS3 credentials and help you setup the secret keys in both .travis and .appveyor.

This secret keys are repo bound in travis and account bound in appveyor, so I cannot do it myself. We will also need to create a new osx-binaries branch to generate the pre-compiled binaries for OSX.

**Comment by peterbraden** [comment]
Yep, how about tomorrow evening CET? I should be able to grab some time then. Thanks!

**Comment by edgarsilva** [comment]
@peterbraden I can make some time from 5:00pm onwards CET(which is arounf 10am my time, Central US Time), any day. Just let me know to schedule it. Tomorrow sounds good for me.

**Comment by peterbraden** [comment]
Great, I'll be around for the next few hours, gimme a ping when is good for you.

**Comment by edgarsilva** [comment]
Hey @peterbraden I'm here, just saw your email you can contact me here on hangouts to set this up, using my github email edgar.osc@gmail.com.

**Pull request merged**
