### PR TITLE
Add CMT

### PR DESCRIPTION
**Pull request by feral913**
add location of source files for cmt in binding.gyp
add source files for cmt at src/CMT
include CMT.h and CMT::Init in init.cc
add an example file cmt-track.js at examples

### CODE REVIEW

**Comment by feral913** [comment]
@peterbraden What's the problem? Doesn't it work?

**Comment by peterbraden** [comment]
The error in travis is:

```
make: Entering directory `/home/travis/build/peterbraden/node-opencv/build'
  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/CMT/common.h:11:0,
                 from ../src/CMT/CMT.h:5,
                 from ../src/init.cc:17:
../src/CMT/logging/log.h: In function ‘std::string NowTime()’:
../src/CMT/logging/log.h:161:14: warning: missing initializer for member ‘tm::tm_min’ [-Wmissing-field-initializers]
     tm r = {0};
```

**Comment by paulovsm** [comment]
@feral913 Did you managed to compile (npm install) the module with your changes? I tried to execute npm install but a couple of errors  were logged.

**Comment by feral913** [comment]
I made it before some month. And few days ago when I checked again, little things are changed in node opencv. So it should be changed also. And I didn't yet.

**Comment by paulovsm** [comment]
I see but I'm trying to the same code you commited on branch "work1". It should you work?

**Comment by feral913** [comment]
No that need to be modified. Actually few days ago I tried to modify it with error log, comparing camshift source. And I succeed to compile but it didn't work, so..I will check more later.

**Comment by feral913** [comment]
@paulovsm I'm done at modifying it. But I'm poor at using github.. So please wait more, if you want to use it.

**Pull request closed without merging**
