### PR TITLE
A packPixels function for WebGL in NW.js

### PR DESCRIPTION
**Pull request by cascade256**
I added a function that packs all the pixels (grayscale or color) into a JS array that can be bound to a WebGL texture for drawing. It isn't very fast (it takes a second or two on a large image), but definitely usable.

There is also a example html file in the examples folder showing how to set up WebGl.

Thanks for creating node-opencv!

### CODE REVIEW

**Comment by peterbraden** [comment]
Looks good, thanks!

**Comment by peterbraden** [comment]
Ah, needs a rebase, I'll merge when I have a chance to get to my home laptop.

**Comment by cascade256** [comment]
Great! I probably won't get around to it soon, but would you mind if I started working on documentation in the wiki?

**Comment by peterbraden** [comment]
Definitely, go for it!

**Comment by Queuecumber** [comment]
Does this actually work? I didn't think we could load the module into a web browser

**Comment by cascade256** [comment]
You can't load it into a normal browser, but it does work with NW.js. NW.js is a version of the Chrome browser with Node.js added. I have run it in that and it works fine. There is also something similar called Electron, but I haven't tried it with that. 

Let me know if you try it out and have any issues.

**Comment by cascade256** [comment]
I am refactoring this to be faster and work better for video, so I think I will close this PR and open a new one when it is ready. Thanks!

**Pull request closed without merging**
