### PR TITLE
failing running detectObject concurrently

### PR DESCRIPTION
**Pull request by kesla**
I don't seem to be able to run detectObject concurrently - and I've added a test for it.

@peterbraden you have any pointers on where and why this is?

### CODE REVIEW

**Comment by kesla** [comment]
Oh, and this seem to be some timing issue - https://travis-ci.org/peterbraden/node-opencv/builds/49976732 is the same code but in that one both 0.10 & 0.11 passed.

It always fails locally (Mac os X)

**Comment by Queuecumber** [comment]
Are you sure this is actually a failure? It looks like it's just detecting something slightly different from what was expected.

**Comment by kesla** [comment]
@Queuecumber Isn't the `FACE_CASCADE` predictable? I'm running it twice on the same image but I get different results.

**Comment by Queuecumber** [comment]
I'm actually not sure, if it's using cascaded classifiers of haar features
then I would think it should be completely deterministic, but I'm not 100%
on that. One good check would be to write this test up using the C++
library and see if it produces the same result when run twice on the same
image and that the result matches what you expect the output to be in your
test case. It's entirely possible that either the JavaScript end or even
the OpenCV implementation isn't resetting it's state properly between runs
which could cause this. That being said when I look at the second result it
is only off by a few pixels so not exactly what I would call incorrect but
certainly unexpected and possibly troubling.

**Comment by kesla** [comment]
@Queuecumber no, the results aren't off by a few pixels here and there. Might they were this run, but locally I've seen the same image having different amount of faces when ran concurrently.

**Comment by Queuecumber** [comment]
Ok I took a look at the detect object code. Nothing stands out to me as the cause of this issue but I don't like that it wraps up a number of complex operations inside of one seemingly simple method call, nor do I like that it's attached to the Matrix prototype as it isn't applicable to matrices in general. Do me a favor and pass the full set of options to it instead of passing an empty object and see if that gives you a deterministic result. Also If you decide to test this against a similar C++ implementation make sure you look at the code in src/CascadeClassifierWrap.cc and follow that exact sequence of operations.

**Comment by AVVS** [comment]
I'm running code like this on Mac OS X 10.10.3 and I always get segfault 11. Version I've tried this with: 0.10.36 and 0.12.1 - result is the same

Things to notice: this works on ubuntu just fine. Image I'm trying this with is - https://avatars1.githubusercontent.com/u/1713617?v=3&s=300

Obviously I pass a matrix. Also I;ve seen cpp code, where it would sample down images that has more than 1 channel to 1 channel, but if I pass a singled-channel image it will crash (in array.cpp code or smth)

```js
var faceProfiles = [
    cv.FACE_CASCADE,
    path.resolve(__dirname, '../../node_modules/opencv/data', 'haarcascade_profileface.xml'),
    path.resolve(__dirname, '../../node_modules/opencv/data', 'haarcascade_frontalface_alt_tree.xml'),
    path.resolve(__dirname, '../../node_modules/opencv/data', 'haarcascade_mcs_eyepair_small.xml'),
    path.resolve(__dirname, '../../node_modules/opencv/data', 'haarcascade_mcs_nose.xml')
];
var faceProfilesLength = faceProfiles.length;

function detectFace(matrix, callback) {

    if (matrix.channels() === 1) {
        return setImmediate(callback, null, false);
    }

    var cursor = 0;
    var faces;

    async.doUntil(
        function checkFace(next) {

            matrix.detectObject(faceProfiles[cursor], {}, function (err, foundFaces) {
                if (err) {
                    return next(err);
                }

                if (foundFaces && foundFaces.length > 0) {
                    faces = foundFaces;
                }

                next();
            });
        },

        function test() {
            return faces || ++cursor < faceProfilesLength;
        },

        function completed(err) {
            if (err) {
                return setImmediate(callback, err);
            }

            if (!faces || faces.length === 0) {
                return setImmediate(callback, null, false);
            }

            return setImmediate(callback, null, faces[0]);
        }
    );

}
```

**Comment by AVVS** [comment]
More information:

```
17:41:42 image-resolve: Started request:  https://secure.gravatar.com/avatar/8caed154c542534e99326ba902ab3c32?s=300

PID 67497 received SIGSEGV for address: 0x0
0   segfault-handler.node               0x00000001008df47f _ZL16segfault_handleriP9__siginfoPv + 287
1   libsystem_platform.dylib            0x00007fff92b75f1a _sigtramp + 26
2   ???                                 0x00003cd8b6560a59 0x0 + 66901469694553
3   opencv.node                         0x000000010559b853 _ZN21AsyncDetectMultiScale16HandleOKCallbackEv + 531
4   node                                0x0000000100393843 uv__work_done + 168
5   node                                0x000000010038a5c6 uv__async_event + 64
6   node                                0x000000010038a74a uv__async_io + 136
7   node                                0x000000010039720e uv__io_poll + 1542
8   node                                0x000000010038ab91 uv_run + 239
9   node                                0x00000001003433f2 _ZN4node5StartEiPPc + 365
10  node                                0x00000001000039b4 start + 52
11  ???                                 0x0000000000000004 0x0 + 4
```

**Comment by AVVS** [comment]
Was able to determine that HandleOkCallback was called twice in cpp code, upgrading NAN to 1.7.0 fixed the issue for me on mac

**Comment by btsimonh** [comment]
see
https://github.com/peterbraden/node-opencv/pull/585
and
https://github.com/peterbraden/node-opencv/pull/587
here I solved a similar issue in a number of async processes; but notably backgroundsubtractor which has a persistent store, and so can't be run on two threads at once.

Main points: 
1/ for classes where there is a persistent store (like backgroundsubtractor, and this one), add a mutex so that the same cv class instance can't be active on two different threads at the same time.
2/ pass a cv::Mat for the input image - then the 'copy' ( mat(mat) )to the local variable claims the data safely until the async class is destroyed (without doing an actual copy of the data).

s

**Pull request closed without merging**
