### PR TITLE
Updated matchTemplate and added an example

### PR DESCRIPTION
**Pull request by salmanulhaq**
issue #387

### CODE REVIEW

**Comment by salmanulhaq** [comment]
@padom checkout the example I wrote. matchTemplate now returns the following array:

1. result: result image (normalized to 8bit single-channel showing the "peaks"
2, 3, 4 and 5 are the ROI: roi_x, roi_y, roi_width and roi_height which is the match location. You can also draw a rectangle on the match by passing 3rd argument as true. Hope this helps

**Comment by padom** [comment]
I saw that is returning array but I can't get him in nodejs. When I whant to show data that is returned in console.log I see just the Matrix object, not array that is returned.

**Comment by salmanulhaq** [comment]
I can get it with output[1] and output[2] etc.

**Comment by padom** [comment]
If I go to install npm module like fork or patch, through package.json, I've got an error.
If I've edited Matrix.cc like you, nothing happens. Can I some how make that this works if i change Matrix.cc file?

**Comment by Feawel** [comment]
Same question here :) (and thanks for the fix !)

**Comment by salmanulhaq** [comment]
@peterbraden can you kindly merge the fix?

**Comment by peterbraden** [comment]
Yep! Sorry for the delay.

**Comment by acinader** [comment]
i don't get this one.  i think that this is overloading matchTemplate too much and diverges the api of node from the underlying library.  See my example in #419 (https://github.com/acinader/node-opencv/blob/40d5036627a830e508eac0ebf8f2c1579dfe3ccb/examples/match-template.js) which draws the rectangle on the match in the same way that the samples in opencv do: https://github.com/Itseez/opencv/blob/master/samples/cpp/mask_tmpl.cpp

if we want to augment node_opencv to make drawing the match, i'd suggest that we add a new method instead of overloading matchTemplate in a way that diverges?

https://github.com/Itseez/opencv/blob/904381c602043270fc864b29dd4749c9c75effbd/modules/imgproc/src/templmatch.cpp#L836

if that seems reasonable, I can try a pr that pulls the draw rectangle out into another method ```drawMatchTemplate``` ??

**Comment by flockonus** [comment]
@acinader thanks for the matchTemplate example, i wouldn't know how to make use of the function  otherwise. Maybe could be merged to this project so may help others easily

**Pull request merged**
