### PR TITLE
Define a native interface for unwrapping the cv:Mat from a Matrix object

### PR DESCRIPTION
**Pull request by mvines**

### CODE REVIEW

**Comment by mvines** [comment]
@peterbraden wdyt?   Thanks!

**Comment by peterbraden** [comment]
I like it. Definitely nice to allow other modules to use the native matrix. Do you have any code that uses it I could look at? Would it be possible to test this?

Thanks!

**Comment by mvines** [comment]
Sure, I added a test in the PR for this: 1cd89cf80912b286260317b27b3577ac3ace2304

**Comment by mvines** [comment]
@peterbraden do you think we can merge this?

**Comment by peterbraden** [comment]
Yep, looks great, thanks!

**Pull request merged**
